name: deployme

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          node-version: 10.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python dependencies
        run: |
          pip3 install mkdocs
          pip3 install mkdocs-material
          pip3 install mkdocs-localsearch
      - name: Build
        run: |
          npm install grunt-cli -g
          npm install .
          grunt
      - name: Generate UUID
        run: echo '::set-output name=ID::$(cat /proc/sys/kernel/random/uuid)'
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: preview-env
          folder: build
          target-folder: ${{ steps.generate-url.outputs.id }}
      - name: Comment link
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Preview: http://choicescriptide.github.io/main/${{ steps.generate-uuid.outputs.id }}/build'
            })
