name: release

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '00 2 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          node-version: 10.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python dependencies
        run: |
          pip3 install mkdocs
          pip3 install mkdocs-material
          pip3 install mkdocs-localsearch
      - name: Build
        run: |
          npm install grunt-cli -g
          npm install .
          grunt
      - name: Archive
        run: zip -r package.nw build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: package.nw
